In [ ]:
# import libery for manipulation
import numpy as np
import pandas as pd
# import libery for Visualization
import matplotlib.pyplot as plt
import seaborn as sns
# import logging
import logging
logging.basicConfig(level = logging.INFO,
                    filename  = 'model.log',
                    filemode= 'w',
                    format = '%(asctime)s - %(levelname)s - %(message)s',
                    force = True)

# filter warning libaries
import warnings


warnings.filterwarnings('ignore')
sns.set_theme(style = 'darkgrid')

In [ ]:
# step 1 : data ingection
df = pd.read_csv(r'/content/ai-impact-jobs-layoff-risk-dataset.csv')
df.sample(frac = 1) # data 100% shuffle

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
5918,54,Master's,3,Healthcare,Nurse,Medium,Mid,70,41,84,Medium,3,9,66,14,Medium
3442,59,Master's,18,Retail,Inventory Analyst,Medium,Mid,23,85,94,Low,2,0,15,9,Low
12756,44,High School,7,Retail,Sales Associate,Medium,Senior,48,39,55,Medium,4,14,23,17,Medium
3338,47,PhD,10,Finance,Auditor,Small,Mid,89,20,22,Medium,2,7,60,11,High
13735,54,Master's,12,Manufacturing,Production Supervisor,Medium,Mid,42,57,23,Low,0,0,23,9,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5558,29,Bachelor's,4,Healthcare,Nurse,Medium,Mid,54,35,97,Low,2,4,35,0,Low
19318,36,Bachelor's,9,Manufacturing,Quality Engineer,Large,Entry,11,100,25,Low,1,2,8,1,Low
18721,32,High School,8,Finance,Financial Analyst,Large,Entry,75,19,38,Medium,2,7,49,24,High
18623,30,High School,8,Logistics,Dispatcher,Medium,Mid,42,69,28,Low,1,2,30,3,Medium
9999,56,High School,1,IT,Data Analyst,Medium,Senior,56,46,47,Medium,5,13,38,5,Medium

In [ ]:
# chacking the data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  object
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  object
 4   Job_Role                    20000 non-null  object
 5   Company_Size                20000 non-null  object
 6   Job_Level                   20000 non-null  object
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  object
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  object
dtypes: int64(9), object(7)
memory usage: 2.4+ MB

In [ ]:
from numpy._core import numeric
# segregate numerical and categorical data
numerical_data = df.select_dtypes(include = np.number)
categorical_data = df.select_dtypes(exclude = np.number)

# calculate descriptive stats  for numerical  colames
from collections import OrderedDict

stats = []

for  i  in numerical_data.columns:

  numerical_stats = OrderedDict({
      'Feature': i,
      'count':df[i].count(),
      'missing values':df[i].isnull().sum() / len(df[i])* 100,
      'mean':df[i].mean(),
      'median':df[i].median(),
      'std':df[i].std(),
      'min':df[i].min(),
      'max':df[i].max(),
      'skewness':df[i].skew(),
      'kurtosis':df[i].kurtosis(),
      'unique values':df[i].nunique(),
      'variance':df[i].var(),
      'Q1':df[i].quantile(0.25),
      'Q3':df[i].quantile(0.75),
      'IQR':df[i].quantile(0.75) - df[i].quantile(0.25),
      })
  stats.append(numerical_stats)
  report = pd.DataFrame(stats)

report

,Feature,count,missing values,mean,median,std,min,max,skewness,kurtosis,unique values,variance,Q1,Q3,IQR
0,Age,20000,0.0,40.36150,40.0,11.526333,21,60,0.012717,-1.195084,40,132.856361,30.0,50.0,20.0
1,Years_of_Experience,20000,0.0,7.26550,7.0,4.720606,0,32,0.369554,-0.393868,27,22.284124,4.0,11.0,7.0
2,Routine_Task_Percentage,20000,0.0,51.88550,52.0,24.437808,10,94,0.005266,-1.196291,85,597.206450,31.0,73.0,42.0
3,Creativity_Requirement,20000,0.0,47.78670,48.0,26.100482,0,100,0.010095,-0.977246,101,681.235165,27.0,69.0,42.0
4,Human_Interaction_Level,20000,0.0,60.05500,62.0,22.267801,20,99,-0.149868,-1.199383,80,495.854968,41.0,79.0,38.0
5,Number_of_AI_Tools_Used,20000,0.0,2.46035,2.0,2.097486,0,10,1.180227,1.621967,11,4.399448,1.0,4.0,3.0
6,AI_Usage_Hours_Per_Week,20000,0.0,6.77395,5.0,6.086370,0,30,1.481313,2.456026,31,37.043904,2.0,10.0,8.0
7,Tasks_Automated_Percentage,20000,0.0,37.22895,35.0,19.995120,4,93,0.432772,-0.604946,90,399.804822,21.0,51.0,30.0
8,AI_Training_Hours,20000,0.0,12.62140,8.0,13.552647,0,79,2.304283,6.468048,80,183.674246,4.0,18.0,14.0